language: go

go:
    - 1.10.1
    - master

script:
    # Test Stringer
    - pushd ./stringer-ci/
    - go test -v ./...
    - popd
    # Test Tail
    - pushd ./tail-ci/
    - go test -v ./...
    - popd
    - pushd ./balanced-BST-ci/
    - go test -v ./...
    - popd
