language: go

go:
    - 1.10.1
    - master

script:
    # Test Stringer
    - pushd ./stringer-ci/
    - go test -v ./...
    - popd
    # Test Tail
    - pushd ./tail-ci/
    - go test -v ./...
    - popd
    - pushd ./balanced-BST-ci/
    - go test -v ./...
    # BST test using exit()
    - mv ./bst_test_driver.go_ ./bst_test_driver.go
    #- sed -e "s///test_driver/test_driver/" -i ./bst.go
    - sed -i '/test_driver()/s/^////g' ./bst.go
    - cat ./bst.go
    - go run ./bst.go ./bst_test_driver.go
    - popd
